// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/nominal_write.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteRequestNominal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequestNominal) Reset() {
	*x = WriteRequestNominal{}
	mi := &file_proto_nominal_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequestNominal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequestNominal) ProtoMessage() {}

func (x *WriteRequestNominal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequestNominal.ProtoReflect.Descriptor instead.
func (*WriteRequestNominal) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequestNominal) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points        *Points                `protobuf:"bytes,3,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_proto_nominal_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{1}
}

func (x *Series) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Series) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Series) GetPoints() *Points {
	if x != nil {
		return x.Points
	}
	return nil
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_proto_nominal_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{2}
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Points struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PointsType:
	//
	//	*Points_DoublePoints
	//	*Points_StringPoints
	//	*Points_IntegerPoints
	//	*Points_DoubleArrayPoints
	//	*Points_StringArrayPoints
	PointsType    isPoints_PointsType `protobuf_oneof:"points_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Points) Reset() {
	*x = Points{}
	mi := &file_proto_nominal_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Points) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Points) ProtoMessage() {}

func (x *Points) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Points.ProtoReflect.Descriptor instead.
func (*Points) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{3}
}

func (x *Points) GetPointsType() isPoints_PointsType {
	if x != nil {
		return x.PointsType
	}
	return nil
}

func (x *Points) GetDoublePoints() *DoublePoints {
	if x != nil {
		if x, ok := x.PointsType.(*Points_DoublePoints); ok {
			return x.DoublePoints
		}
	}
	return nil
}

func (x *Points) GetStringPoints() *StringPoints {
	if x != nil {
		if x, ok := x.PointsType.(*Points_StringPoints); ok {
			return x.StringPoints
		}
	}
	return nil
}

func (x *Points) GetIntegerPoints() *IntegerPoints {
	if x != nil {
		if x, ok := x.PointsType.(*Points_IntegerPoints); ok {
			return x.IntegerPoints
		}
	}
	return nil
}

func (x *Points) GetDoubleArrayPoints() *DoubleArrayPoints {
	if x != nil {
		if x, ok := x.PointsType.(*Points_DoubleArrayPoints); ok {
			return x.DoubleArrayPoints
		}
	}
	return nil
}

func (x *Points) GetStringArrayPoints() *StringArrayPoints {
	if x != nil {
		if x, ok := x.PointsType.(*Points_StringArrayPoints); ok {
			return x.StringArrayPoints
		}
	}
	return nil
}

type isPoints_PointsType interface {
	isPoints_PointsType()
}

type Points_DoublePoints struct {
	DoublePoints *DoublePoints `protobuf:"bytes,1,opt,name=double_points,json=doublePoints,proto3,oneof"`
}

type Points_StringPoints struct {
	StringPoints *StringPoints `protobuf:"bytes,2,opt,name=string_points,json=stringPoints,proto3,oneof"`
}

type Points_IntegerPoints struct {
	IntegerPoints *IntegerPoints `protobuf:"bytes,3,opt,name=integer_points,json=integerPoints,proto3,oneof"`
}

type Points_DoubleArrayPoints struct {
	DoubleArrayPoints *DoubleArrayPoints `protobuf:"bytes,4,opt,name=double_array_points,json=doubleArrayPoints,proto3,oneof"`
}

type Points_StringArrayPoints struct {
	StringArrayPoints *StringArrayPoints `protobuf:"bytes,5,opt,name=string_array_points,json=stringArrayPoints,proto3,oneof"`
}

func (*Points_DoublePoints) isPoints_PointsType() {}

func (*Points_StringPoints) isPoints_PointsType() {}

func (*Points_IntegerPoints) isPoints_PointsType() {}

func (*Points_DoubleArrayPoints) isPoints_PointsType() {}

func (*Points_StringArrayPoints) isPoints_PointsType() {}

type DoublePoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*DoublePoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoublePoints) Reset() {
	*x = DoublePoints{}
	mi := &file_proto_nominal_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoublePoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoublePoints) ProtoMessage() {}

func (x *DoublePoints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoublePoints.ProtoReflect.Descriptor instead.
func (*DoublePoints) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{4}
}

func (x *DoublePoints) GetPoints() []*DoublePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type StringPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*StringPoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPoints) Reset() {
	*x = StringPoints{}
	mi := &file_proto_nominal_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPoints) ProtoMessage() {}

func (x *StringPoints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPoints.ProtoReflect.Descriptor instead.
func (*StringPoints) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{5}
}

func (x *StringPoints) GetPoints() []*StringPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type IntegerPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*IntegerPoint        `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerPoints) Reset() {
	*x = IntegerPoints{}
	mi := &file_proto_nominal_write_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerPoints) ProtoMessage() {}

func (x *IntegerPoints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerPoints.ProtoReflect.Descriptor instead.
func (*IntegerPoints) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{6}
}

func (x *IntegerPoints) GetPoints() []*IntegerPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type DoublePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoublePoint) Reset() {
	*x = DoublePoint{}
	mi := &file_proto_nominal_write_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoublePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoublePoint) ProtoMessage() {}

func (x *DoublePoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoublePoint.ProtoReflect.Descriptor instead.
func (*DoublePoint) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{7}
}

func (x *DoublePoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DoublePoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StringPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPoint) Reset() {
	*x = StringPoint{}
	mi := &file_proto_nominal_write_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPoint) ProtoMessage() {}

func (x *StringPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPoint.ProtoReflect.Descriptor instead.
func (*StringPoint) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{8}
}

func (x *StringPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StringPoint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IntegerPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerPoint) Reset() {
	*x = IntegerPoint{}
	mi := &file_proto_nominal_write_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerPoint) ProtoMessage() {}

func (x *IntegerPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerPoint.ProtoReflect.Descriptor instead.
func (*IntegerPoint) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{9}
}

func (x *IntegerPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IntegerPoint) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DoubleArrayPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*DoubleArrayPoint    `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleArrayPoints) Reset() {
	*x = DoubleArrayPoints{}
	mi := &file_proto_nominal_write_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleArrayPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleArrayPoints) ProtoMessage() {}

func (x *DoubleArrayPoints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleArrayPoints.ProtoReflect.Descriptor instead.
func (*DoubleArrayPoints) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{10}
}

func (x *DoubleArrayPoints) GetPoints() []*DoubleArrayPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type StringArrayPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*StringArrayPoint    `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArrayPoints) Reset() {
	*x = StringArrayPoints{}
	mi := &file_proto_nominal_write_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArrayPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArrayPoints) ProtoMessage() {}

func (x *StringArrayPoints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArrayPoints.ProtoReflect.Descriptor instead.
func (*StringArrayPoints) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{11}
}

func (x *StringArrayPoints) GetPoints() []*StringArrayPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type DoubleArrayPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         []float64              `protobuf:"fixed64,2,rep,packed,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleArrayPoint) Reset() {
	*x = DoubleArrayPoint{}
	mi := &file_proto_nominal_write_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleArrayPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleArrayPoint) ProtoMessage() {}

func (x *DoubleArrayPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleArrayPoint.ProtoReflect.Descriptor instead.
func (*DoubleArrayPoint) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{12}
}

func (x *DoubleArrayPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DoubleArrayPoint) GetValue() []float64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type StringArrayPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         []string               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArrayPoint) Reset() {
	*x = StringArrayPoint{}
	mi := &file_proto_nominal_write_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArrayPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArrayPoint) ProtoMessage() {}

func (x *StringArrayPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nominal_write_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArrayPoint.ProtoReflect.Descriptor instead.
func (*StringArrayPoint) Descriptor() ([]byte, []int) {
	return file_proto_nominal_write_proto_rawDescGZIP(), []int{13}
}

func (x *StringArrayPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StringArrayPoint) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_nominal_write_proto protoreflect.FileDescriptor

const file_proto_nominal_write_proto_rawDesc = "" +
	"\n" +
	"\x19proto/nominal_write.proto\x12\x1aio.nominal.scout.api.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\x13WriteRequestNominal\x12:\n" +
	"\x06series\x18\x01 \x03(\v2\".io.nominal.scout.api.proto.SeriesR\x06series\"\xfe\x01\n" +
	"\x06Series\x12=\n" +
	"\achannel\x18\x01 \x01(\v2#.io.nominal.scout.api.proto.ChannelR\achannel\x12@\n" +
	"\x04tags\x18\x02 \x03(\v2,.io.nominal.scout.api.proto.Series.TagsEntryR\x04tags\x12:\n" +
	"\x06points\x18\x03 \x01(\v2\".io.nominal.scout.api.proto.PointsR\x06points\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1d\n" +
	"\aChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xcf\x03\n" +
	"\x06Points\x12O\n" +
	"\rdouble_points\x18\x01 \x01(\v2(.io.nominal.scout.api.proto.DoublePointsH\x00R\fdoublePoints\x12O\n" +
	"\rstring_points\x18\x02 \x01(\v2(.io.nominal.scout.api.proto.StringPointsH\x00R\fstringPoints\x12R\n" +
	"\x0einteger_points\x18\x03 \x01(\v2).io.nominal.scout.api.proto.IntegerPointsH\x00R\rintegerPoints\x12_\n" +
	"\x13double_array_points\x18\x04 \x01(\v2-.io.nominal.scout.api.proto.DoubleArrayPointsH\x00R\x11doubleArrayPoints\x12_\n" +
	"\x13string_array_points\x18\x05 \x01(\v2-.io.nominal.scout.api.proto.StringArrayPointsH\x00R\x11stringArrayPointsB\r\n" +
	"\vpoints_type\"O\n" +
	"\fDoublePoints\x12?\n" +
	"\x06points\x18\x01 \x03(\v2'.io.nominal.scout.api.proto.DoublePointR\x06points\"O\n" +
	"\fStringPoints\x12?\n" +
	"\x06points\x18\x01 \x03(\v2'.io.nominal.scout.api.proto.StringPointR\x06points\"Q\n" +
	"\rIntegerPoints\x12@\n" +
	"\x06points\x18\x01 \x03(\v2(.io.nominal.scout.api.proto.IntegerPointR\x06points\"]\n" +
	"\vDoublePoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"]\n" +
	"\vStringPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"^\n" +
	"\fIntegerPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"Y\n" +
	"\x11DoubleArrayPoints\x12D\n" +
	"\x06points\x18\x01 \x03(\v2,.io.nominal.scout.api.proto.DoubleArrayPointR\x06points\"Y\n" +
	"\x11StringArrayPoints\x12D\n" +
	"\x06points\x18\x01 \x03(\v2,.io.nominal.scout.api.proto.StringArrayPointR\x06points\"b\n" +
	"\x10DoubleArrayPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x01R\x05value\"b\n" +
	"\x10StringArrayPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x03(\tR\x05valueBP\n" +
	"\x1aio.nominal.scout.api.protoP\x01Z0github.com/nominal-io/nominal-streaming-go/protob\x06proto3"

var (
	file_proto_nominal_write_proto_rawDescOnce sync.Once
	file_proto_nominal_write_proto_rawDescData []byte
)

func file_proto_nominal_write_proto_rawDescGZIP() []byte {
	file_proto_nominal_write_proto_rawDescOnce.Do(func() {
		file_proto_nominal_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nominal_write_proto_rawDesc), len(file_proto_nominal_write_proto_rawDesc)))
	})
	return file_proto_nominal_write_proto_rawDescData
}

var file_proto_nominal_write_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_nominal_write_proto_goTypes = []any{
	(*WriteRequestNominal)(nil),   // 0: io.nominal.scout.api.proto.WriteRequestNominal
	(*Series)(nil),                // 1: io.nominal.scout.api.proto.Series
	(*Channel)(nil),               // 2: io.nominal.scout.api.proto.Channel
	(*Points)(nil),                // 3: io.nominal.scout.api.proto.Points
	(*DoublePoints)(nil),          // 4: io.nominal.scout.api.proto.DoublePoints
	(*StringPoints)(nil),          // 5: io.nominal.scout.api.proto.StringPoints
	(*IntegerPoints)(nil),         // 6: io.nominal.scout.api.proto.IntegerPoints
	(*DoublePoint)(nil),           // 7: io.nominal.scout.api.proto.DoublePoint
	(*StringPoint)(nil),           // 8: io.nominal.scout.api.proto.StringPoint
	(*IntegerPoint)(nil),          // 9: io.nominal.scout.api.proto.IntegerPoint
	(*DoubleArrayPoints)(nil),     // 10: io.nominal.scout.api.proto.DoubleArrayPoints
	(*StringArrayPoints)(nil),     // 11: io.nominal.scout.api.proto.StringArrayPoints
	(*DoubleArrayPoint)(nil),      // 12: io.nominal.scout.api.proto.DoubleArrayPoint
	(*StringArrayPoint)(nil),      // 13: io.nominal.scout.api.proto.StringArrayPoint
	nil,                           // 14: io.nominal.scout.api.proto.Series.TagsEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_proto_nominal_write_proto_depIdxs = []int32{
	1,  // 0: io.nominal.scout.api.proto.WriteRequestNominal.series:type_name -> io.nominal.scout.api.proto.Series
	2,  // 1: io.nominal.scout.api.proto.Series.channel:type_name -> io.nominal.scout.api.proto.Channel
	14, // 2: io.nominal.scout.api.proto.Series.tags:type_name -> io.nominal.scout.api.proto.Series.TagsEntry
	3,  // 3: io.nominal.scout.api.proto.Series.points:type_name -> io.nominal.scout.api.proto.Points
	4,  // 4: io.nominal.scout.api.proto.Points.double_points:type_name -> io.nominal.scout.api.proto.DoublePoints
	5,  // 5: io.nominal.scout.api.proto.Points.string_points:type_name -> io.nominal.scout.api.proto.StringPoints
	6,  // 6: io.nominal.scout.api.proto.Points.integer_points:type_name -> io.nominal.scout.api.proto.IntegerPoints
	10, // 7: io.nominal.scout.api.proto.Points.double_array_points:type_name -> io.nominal.scout.api.proto.DoubleArrayPoints
	11, // 8: io.nominal.scout.api.proto.Points.string_array_points:type_name -> io.nominal.scout.api.proto.StringArrayPoints
	7,  // 9: io.nominal.scout.api.proto.DoublePoints.points:type_name -> io.nominal.scout.api.proto.DoublePoint
	8,  // 10: io.nominal.scout.api.proto.StringPoints.points:type_name -> io.nominal.scout.api.proto.StringPoint
	9,  // 11: io.nominal.scout.api.proto.IntegerPoints.points:type_name -> io.nominal.scout.api.proto.IntegerPoint
	15, // 12: io.nominal.scout.api.proto.DoublePoint.timestamp:type_name -> google.protobuf.Timestamp
	15, // 13: io.nominal.scout.api.proto.StringPoint.timestamp:type_name -> google.protobuf.Timestamp
	15, // 14: io.nominal.scout.api.proto.IntegerPoint.timestamp:type_name -> google.protobuf.Timestamp
	12, // 15: io.nominal.scout.api.proto.DoubleArrayPoints.points:type_name -> io.nominal.scout.api.proto.DoubleArrayPoint
	13, // 16: io.nominal.scout.api.proto.StringArrayPoints.points:type_name -> io.nominal.scout.api.proto.StringArrayPoint
	15, // 17: io.nominal.scout.api.proto.DoubleArrayPoint.timestamp:type_name -> google.protobuf.Timestamp
	15, // 18: io.nominal.scout.api.proto.StringArrayPoint.timestamp:type_name -> google.protobuf.Timestamp
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_nominal_write_proto_init() }
func file_proto_nominal_write_proto_init() {
	if File_proto_nominal_write_proto != nil {
		return
	}
	file_proto_nominal_write_proto_msgTypes[3].OneofWrappers = []any{
		(*Points_DoublePoints)(nil),
		(*Points_StringPoints)(nil),
		(*Points_IntegerPoints)(nil),
		(*Points_DoubleArrayPoints)(nil),
		(*Points_StringArrayPoints)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nominal_write_proto_rawDesc), len(file_proto_nominal_write_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_nominal_write_proto_goTypes,
		DependencyIndexes: file_proto_nominal_write_proto_depIdxs,
		MessageInfos:      file_proto_nominal_write_proto_msgTypes,
	}.Build()
	File_proto_nominal_write_proto = out.File
	file_proto_nominal_write_proto_goTypes = nil
	file_proto_nominal_write_proto_depIdxs = nil
}
